### ISSUE TITLE
Implementing ESRI Swipe widget

### ISSUE THREAD

**Issue by PhilipGriffith** [FREAC/LABINS#127]
We're interested in testing a swipe widget for the LABINS map.

- For reference, you can see a simple example of the swipe widget's functionality by using the central widget button in [this FNAI map](https://www.fnai.org/webmaps/ConLandsMap/).

Documentation for the widget can be found [here](https://developers.arcgis.com/javascript/latest/api-reference/esri-widgets-Swipe.html).

Initially, we'd like the tool to swipe **all** of the layers from the map, leaving only the basemap beneath visible. In terms of the widget settings, that may simply mean leaving the `trailingLayers` property empty, but I'm not 100% sure about that.

The only snag I can see is that the current version of the widget does not support swiping a `GroupLayer`, though I'm not sure whether those have been implemented in the current version of LABINS.

Layers we want to start with: [labinsLayer, ngsLayer, swfwmdLayer, CCCLLayer]

Clinton, would you be able to implement this in a new branch off of the master? Thanks!

**Comment by clintonlunn** [comment]
It doesn't look like we've used grouplayers in the current version of LABINS. To my knowledge, we don't use grouplayers anywhere.

**Comment by shodge17** [comment]
Umm... I would have thought that the "labins data" piece of the Layerlist would constitute a group.  You can turn on and off the "group" without turning off each layer.

**Comment by PhilipGriffith** [comment]
The layers from the REST service are created as `MapImageLayer` objects; we can manipulate them as a group because each data layer within the MapImageLayer is considered a "sublayer" of the service. I'm not sure if `GroupLayer` objects are just there for convenience, but they don't appear in our code for the site (though they do appear in the `sample.html` file, which really threw me off for a second! lol)

**Comment by shodge17** [comment]
when you get started on this one I need to know if the swipe is a all or nothing kind of thing.  IE do you simply swipe away all layers except the basemap, or could you do something like swipe away everything except the PLSS points. 

Ideally the user could decide which layers they want left after the swipe.  I dont want you spending a lot of time on this last idea (user decides what is left after the swipe) because I suspect that will be a big challenge.

**Comment by PhilipGriffith** [comment]
You're able to choose which layers are included in the "swipe" functionality by putting them into lists of `leadingLayers` (those initially displayed) and `trailingLayers` (those displayed after removal of the others).

I'm not sure I've ever seen an application that allows you to choose which layers you swipe between. I think this is because the swipe feature is usually used to compare layer data with information baked into the basemap, and not to compare layer data with other layer data.

**Comment by clintonlunn** [comment]
Picking and choosing which layers you want to swipe is _probably_ possible, but would add a lot of complexity. Looking at this now

**Comment by clintonlunn** [comment]
Some additional work needs to be done to implement this. The swipe feature is only available at > 4.13. Right now both the enhancements branch and master branch are on 4.10. We will need to update to at least that version to use this widget. 

@PhilipGriffith You had initially said to branch off of master to do this work. Is this because you want it to be merged in before the next release? Or can I branch off of the enhancements branch and do the upgrade and swipe widget development from there?

**Comment by PhilipGriffith** [comment]
I misspoke: this is definitely an enhancement for the future, so I would say branch off of the "enhancements" branch and develop the widget from there.

I was also mistaken in believing that the application was already using a compatible version of the API. Since we're not, we'll need to make sure that everything works with version 4.13 (or higher?) before we begin merging any enhancements into the master. It may even be necessary to (1) create a new branch off of the master, (2) upgrade and test that code, (3) merge the enhancements into the new, upgraded branch, then (4) merge all of it back into the master. (I hope that makes sense!)

**Comment by clintonlunn** [comment]
@PhilipGriffith that makes sense.

I did some quick testing of it and it seems that 4.14 does not immediately work...getting some error messages that are outside our codebase (errors in the mapview.js file) and it's causing some seriously slow performance. I need to do some more extensive testing to make this upgrade. 4.10 to 4.14 are all minor releases so there _should_ not be any breaking changes, but who know...

**Comment by shodge17** [comment]
I would hate to get stuck with an "old" version of the API.  I guess we will need to figure out what piece is causing the break and go from there.  Although this is not a must have feature, there will be some feature in the near future that will require an upgrade so we might as well figure it out now.

**Comment by clintonlunn** [comment]
I found it's something in our code somehwere within the overview map portion of the code. trying to hammer out what it is.

**Comment by clintonlunn** [comment]
@PhilipGriffith I'm not sure that branching off of master would be necessary. Since we want all of the code from enhancements in the next release, (I think) then we should branch off of enhancements, do the work there, merge back into enhancements, then finally merge into master so master will essentially become the enhancements branch after the next release. Does that sound correct?

**Comment by PhilipGriffith** [comment]
That sounds both better and correct. lol

**Comment by clintonlunn** [comment]
I created a ticket to address this change #128

**Comment by PhilipGriffith** [comment]
That also sounds both better and correct. :)

**Comment by shodge17** [comment]
I know we talked about ideally allowing the user to select layers for the swipe, but the more I think about it the more I think some of the newbies are going to think there are a lot of clicks just to get to what I want.

1) I like the ability to set the leading and trailing layers so I want this code left in there.  I am thinking of the novice user now and I think they may not get the concept at first.  I think for this year we get them acquainted with a default version and then for an enhancement we add in the logic you have now.  So see if you can figure out an easy way to leave all your code in there but just don't load it now.  I would rather you not comment it out if possible because it quickly can get lost and we think lets get rid of all the commented out code.

2) as a starter I want a version where the user can't pick the layers.  The layers in the leading need to be all the layers and the trailing needs to be left to null

3) when you open the swipe I want it turned on and the user has no options.

4) I see there currently is no way to "get out of swipemode".  How easy would it be to but the swipe in an "Expand" element and add it under the measure tool

**Comment by clintonlunn** [comment]
What you're proposing simplifies things a bit. I'll add a button in the measurement widget to do a slimmed down swipe. 

I have more improvements locally. I think it would be worth it to continue pursuing those and hold those changes back for a later release.

**Comment by shodge17** [comment]
I was hoping for a new button _under_ the measure tool not part of the measure tool.  Can you do that?

**Comment by clintonlunn** [comment]
Yep I can do that. I'm aiming to complete by end of week.

**Comment by clintonlunn** [comment]
@shodge17 what do you think of this? I was a little short on time (on my lunch break), but I can certainly tidy it up once we come to a consensus on this.

still todo:
* remove more complicated swipe panel
* put widget button under measurement (it's currently above home btn)
* finalize which layers we want leading and which layers we want trailing

**Comment by shodge17** [comment]
I agree 
as for the layers, lets just see if you put all the layers in the leading so when the swipe is used it removes everything down to the basemap.

**Comment by clintonlunn** [comment]
done

**Comment by shodge17** [comment]
I think all you need to do to finish this is to either take the swipe option out of the main menu, or make it behave the same way the icon does.

**Comment by clintonlunn** [comment]
I removed the enhanced swipe code and removed the menu and panel html. i will push up another branch that contains that code so we can continue working on this new enhanced swipe feature.

**Comment by clintonlunn** [comment]
The base swipe widget should be good to go.

**Comment by shodge17** [comment]
I agree
