### ISSUE TITLE
"Un-hide" legend and layerlist

### ISSUE THREAD

**Issue by shodge17** [FREAC/LABINS#184]
I think we should be able to access the legend and layerlist options on small devices.  Was there a reason they are hidden now?  can you just remove the hidden-xs c;lass to fix the issue?

**Comment by clintonlunn** [comment]
We can access the legend and layerlist options, they're just hidden into the hamburger menu at the top. I also "tested" this on 

![image](https://user-images.githubusercontent.com/24685932/104263194-1835d080-5457-11eb-9307-8de7630a2f04.png)
![image](https://user-images.githubusercontent.com/24685932/104263129-f1779a00-5456-11eb-8ce5-8a4e18e206f8.png)
![image](https://user-images.githubusercontent.com/24685932/104263148-00f6e300-5457-11eb-98d7-1791cbe23389.png)


However, I just tested this on my iPhone SE, which is a very small phone. It isn't very usable with these legend or layerlist. I think this issue is beside your original point though. 
![image](https://user-images.githubusercontent.com/24685932/104263477-aca03300-5457-11eb-8560-978514b26e92.png)
![image](https://user-images.githubusercontent.com/24685932/104263650-fdb02700-5457-11eb-88ec-3da3d6771820.png)

**Comment by shodge17** [comment]
Some how missed that.... I think we are good then.  Sorry about that,.

**Comment by clintonlunn** [comment]
No problem! Good to know there was no issue afterall.
