### ISSUE TITLE
Certified Corner labels dont show

### ISSUE THREAD

**Issue by shodge17** [FREAC/LABINS#204]
this is due to the join changing the name reverences.  Here is what it needs to look like:
      id: 2,
      title: "Certified Corners",
      visible: true,
      popupEnabled: false,
      minScale: minimumDrawScale,
      labelingInfo: haloLabelInfo("[base_and_survey.sde.pls_ptp_master_3857.blmid]", [0, 0, 255, 255]),
      labelsVisible: false
    }, {

**Comment by shodge17** [comment]
If you update the code as I show above, you get a label for each related ccr record.  IE if a corner has 3 documents associated with it you get 3 labels.  I there are no related records you still to get the appropriate label.

**Comment by shodge17** [comment]
I think I stumbled on the answer.  Just label the newCCRLayer instead of the original one found in the master map service.  For whatever reason, it only show one label.  

This causes the label icon in the layerList to not work

**Comment by clintonlunn** [comment]
I see what you mean. I can say for sure the labels button on the layerlist for the CCR records doesn't work this way because that button is trying to flip on the labels for the old CCR layer. This can probably be accounted for fairly easily. I think an approach like this will work, but it leaves the old CCR layer with only 1 remaining use: to display white/black points on the map.  A good enhancement for the future (or now if we can find a solution) would be to symbolize/label/query only with the new CCR layer

**Comment by clintonlunn** [comment]
Good morning @shodge17, looks like you have possibly changed the old CCR layer to prevent multiple labels from showing?

**Comment by shodge17** [comment]
I need you to call me about this issue when you have at least 15 minutes.  I dont care when -- ie after 5 is ok if that works best

**Comment by clintonlunn** [comment]
@shodge17 Sure, I sent an email to set something up.
