### ISSUE TITLE
Data query - by Tide Station

### ISSUE THREAD

**Issue by shodge17** [FREAC/LABINS#70]
Try this: 
1) open the data query panel
2) select tide stations
3) select Bay county
4) hit Submit
Nothing happens.
if you add Bunker to the selection it blanks out the county - this is good
now hit submit - still nothing happens
if you enter 9329 and submit it will make sure the other search areas are blanks and it will find the station that is in Bay county - Bunker quad.
I think what we want to happen on a submit with Bay county selected is for it to find the 33 stations in the county and let you toggle through them.  
Same strategy for a quad query.

**Comment by clintonlunn** [comment]
This issue has been fixed in the MapCon branch. The data query process was broken by checking to see if there are results returned, so that's why nothing was happening when the user hit submit. 

For this, the submit is only acting on a text search. When a dropdown selection is chosen, it finds all of the tide stations within the county/quad without pressing submit. If a text search is entered, the submit button is necessary to run the query.
