### ISSUE TITLE
Layer scale visibility

### ISSUE THREAD

**Issue by clintonlunn** [FREAC/LABINS#74]
There is no way to know when a layer will become visible. Currently, the user must zoom in until a layer becomes visible and there is no indication on map load to say when a layer will become visible.

**Comment by PhilipGriffith** [comment]
I'm not sure this is an issue any more. People are familiar with the previous version of the application, as well as other mapping applications like Google Maps that don't show detailed layers until they zoom in, so I would imagine they'd expect the same here. Moreover, zooming to a township and range extent brings you to a scale where the layers are visible. Finally, I think this sort of information is better placed in a user tutorial, rather than in the application itself.
